apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-secret
  annotations:
     serving.kubeflow.org/s3-endpoint: minio-service.kubeflow:9000
     serving.kubeflow.org/s3-usehttps: "0" # Default: 1. Must be 0 when testing with MinIO!
type: Opaque
data:
  awsAccessKeyID: bWluaW8= # base64 encoded of minio
  awsSecretAccessKey: bWluaW8xMjM= # base64 encoded of minio123
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: minio-s3-secret